
#' Copy run directories
#'
#' Functions for exporting/copying run directories and run artifact files.
#'
#' @inheritParams run_info
#'
#' @param to Name of parent directory to copy run(s) into. Defaults to the
#'   current working directory.
#'
#' @param rename Rename run directory after copying. If not specified this
#'   defaults to the basename of the run directory (e.g.
#'   "2017-09-24T10-54-00Z").
#'
#' @details Use `copy_run` to copy a single run directory
#'
#'   Use `copy_run_files` to copy only files saved/generated by a training run
#'   script (e.g. saved models, checkpoints, etc.).
#'
#'   Use `copy_runs` to copy multiple run directories.
#'
#' @return Logical vector indicating which operation succeeded for each of the
#'   run directories specified.
#'
#' @family run management
#'
#' @examples \dontrun{
#'
#' # export a run directory
#' copy_run("runs/2017-09-24T10-54-00Z", to = "exported-runs")
#'
#' # export to the current working directory then rename
#' copy_run("runs/2017-09-24T10-54-00Z", rename = "best-run")
#'
#' # export artifact files to the current working directory then rename
#' copy_run_files("runs/2017-09-24T10-54-00Z", rename = "best-model")
#'
#' # export the best 3 runs (in terms of eval accuracy)
#' copy_runs(ls_runs(order = eval_acc)[1:3,], to = "best-runs")
#'
#' }
#' @export
copy_run <- function(run_dir, to = ".", rename = NULL) {
  do_copy_run(run_dir, to, rename)
}


#' @rdname copy_run
#' @export
copy_run_files <- function(run_dir, to = ".", rename = NULL) {
  do_copy_run(run_dir, to, rename, remove = c("tfruns.d", "logs", "plots"))
}


#' @param run_dirs One or more run directories to copy into the
#'   parent directory specified in `to`.
#'
#' @rdname copy_run
#' @export
copy_runs <- function(run_dirs, to) {

  # convert to run_dirs
  run_dirs <- as_run_dir(run_dirs)

  # create to if it doesn't exist
  if (!file.exists(to))
    dir.create(to, recursive = TRUE)

  # to must be a directory
  if (!utils::file_test("-d", to))
    stop("The 'to' argument of copy_runs must be a directory")

  # copy the runs
  result <- file.copy(run_dirs, to, recursive = TRUE)

  # print status
  runs_copied <- length(which(result))
  message(sprintf('%d run directories copied to "%s"', runs_copied, to))

  # return status
  invisible(result)
}


do_copy_run <- function(run_dir, to = ".", rename = NULL, remove = NULL) {

  # resolve run_dir
  run_dir <- as_run_dir(run_dir)

  # must be length 1
  if (length(run_dir) != 1)
    stop("You must pass a single run directory to copy_run")
  if (length(to) != 1)
    stop("You must pass a single 'to' directory to copy_run")

  # test directory existence
  if (!utils::file_test("-d", run_dir))
    stop(run_dir, " is not a valid run directory")

  # create to if it doesn't exist
  if (!utils::file_test("-d",to))
    dir.create(to, recursive = TRUE)

  # copy run dir to target and rename
  if (file.copy(run_dir, to = to, recursive = TRUE, overwrite = TRUE, copy.date = TRUE)) {
    if (!is.null(rename)) {
      rename_path <- file.path(to, rename)
      if (utils::file_test("-d", rename_path))
        unlink(rename_path, recursive = TRUE)
      result <- file.rename(file.path(to, basename(run_dir)), rename_path)
    } else {
      result <- TRUE
    }
  } else {
    result <- FALSE
  }

  # perform remove if requested
  if (result && !is.null(remove))
    unlink(file.path(to, rename, remove), recursive = TRUE)

  # return
  invisible(result)
}


