
#' Copy run directories
#'
#' Functions for exporting/copying run directories and run artifact files.
#'
#' @inheritParams run_info
#'
#' @param to Name of directory to copy into. For `copy_run` and `copy_run_files`
#'   this is is a single directory which run files will be copied into. For
#'   `copy_runs` this is a parent directory to copy multiple runs into as
#'   subdirectories.
#'
#' @param overwrite Whether to overwrite an existing `to` directory The default
#'   is "confirm", which will promot in the case that `to` already exists.
#'
#' @details Use `copy_run` to copy a single run directory to a named target
#'   directory.
#'
#'   Use `copy_run_files` to copy only files saved/generated by a training run
#'   script (e.g. saved models, checkpoints, etc.).
#'
#'   Use `copy_runs` to copy multiple runs into a parent directory.
#'
#' @return Logical vector indicating which operation succeeded for each of the
#'   run directories specified.
#'
#' @family run management
#'
#' @examples \dontrun{
#'
#' # export a run directory
#' copy_run("runs/2017-09-24T10-54-00Z", to = "best-run")
#'
#' # export the artifact files from a run directory
#' copy_run_files("runs/2017-09-24T10-54-00Z", "best-model")
#'
#' # export the best (in terms of eval accuracy)
#' copy_runs(ls_runs(order = eval_acc)[1:3,], to = "best_eval_acc")
#'
#' }
#' @export
copy_run <- function(run_dir, to, overwrite = "confirm") {

  # resolve run_dir
  run_dir <- as_run_dir(run_dir)

  # must be length 1
  if (length(run_dir) != 1)
    stop("You must pass a single run directory to copy_run")
  if (length(to) != 1)
    stop("You must pass a single 'to' directory to copy_run")

  # test directory existence
  if (!utils::file_test("-d", run_dir))
    stop(run_dir, " is not a valid directory")

  # test for to existing
  if (file.exists(to)) {
    if (overwrite == FALSE)
      stop("Specified target directory '", to, "' already exists")
    else {
      if (overwrite == "confirm") {
        prompt <- readline(sprintf(paste0(
          "Target directory '%s' already exists. Do you want to remove ",
           "the existing directory [y/n]: "), to))
        if (tolower(prompt) != 'y') {
          message("Run directory not copied")
          return(invisible(FALSE))
        } else {
          overwrite <- TRUE
        }
      }
      if (isTRUE(overwrite)) {
        unlink(to, recursive = TRUE)
      } else {
        stop('Invalid value for overwrite (must be TRUE, FALSE, or "confirm")')
      }
    }
  }

  # test for parent of target existing
  to_dir <- dirname(to)
  if (!utils::file_test("-d", to_dir))
    stop("Target directory '", to_dir, " does not exist.")

  # copy run dir to target
  result <- file.copy(run_dir, to = to_dir, recursive = TRUE, copy.date = TRUE) &&
            file.rename(file.path(to_dir, basename(run_dir)),
                        file.path(to_dir, basename(to)))

  # return result invisibly
  invisible(result)
}


#' @rdname copy_run
#' @export
copy_run_files <- function(run_dir, to, overwrite = "confirm") {
  # copy the entire run then remove the meta-directories
  if (copy_run(run_dir, to, overwrite = overwrite)) {
    unlink(file.path(to, c("tfruns.d", "logs", "plots")), recursive = TRUE)
    invisible(TRUE)
  } else {
    invisible(FALSE)
  }
}


#' @param run_dirs One or more run directories to copy into the
#'   parent directory specified in `to`.
#'
#' @rdname copy_run
#' @export
copy_runs <- function(run_dirs, to) {

  # convert to run_dirs
  run_dirs <- as_run_dir(run_dirs)

  # create to if it doesn't exist
  if (!file.exists(to))
    dir.create(to, recursive = TRUE)

  # to must be a directory
  if (!utils::file_test("-d", to))
    stop("The 'to' argument of copy_runs must be a directory")

  # copy the runs
  result <- file.copy(run_dirs, to, recursive = TRUE)

  # print status
  runs_copied <- length(which(result))
  message(sprintf('%d run directories copied to "%s"', runs_copied, to))

  # return status
  invisible(result)
}

